#!/bin/bash

if [ -f /root/.kibana.passwd ]; then
    cat <<EOF
To access Kibana, open https://$(/usr/local/bin/oc-metadata --cached PUBLIC_IP_ADDRESS)/.
Login with user kibana and password -> $(cat /root/.kibana.passwd) <-
EOF
fi

cat <<EOF
You can hide this message on the next connection by deleting the $0 file.
EOF
